name: angular_gallery_section
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.4.0
  angular: ^7.0.1
  angular_components: ^1.0.0
  angular_gallery:
    path: ../angular_gallery
  build: ^2.1.1
  build_config: ^1.0.0
  glob: ^2.0.2
  markdown: ^4.0.0
  #mustache: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'

  ngsecurity: 
    git: https://github.com/angulardart-community/ngsecurity

dependency_overrides:
  angular_components:
    path: ../angular_components
