name: angular_gallery
publish_to: none
environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  angular: ^7.0.1
  angular_components: ^1.0.0
  angular_forms: ^4.0.0
  angular_router: ^3.0.0
  build: ^2.1.1
  build_config: ^1.0.0
  mustache: ^1.0.0
  ngsecurity:
    git: https://github.com/angulardart-community/ngsecurity.git

dependency_overrides:
  angular_components:
    path: ../angular_components
